spring:
  application:
    name: fc-hello-websocket-chatting
  profiles:
    active: local
    group:
      local: console-logging, low-level-logging
      dev: file-logging, high-level-logging

server:
  servlet:
    encoding:
      force-response: true